### ISSUE TITLE
GraalVM 19.0.0 - what version tag should we use to avoid confusing SDKMAN users?

### ISSUE THREAD

**Issue by wololock** [sdkman/sdkman-db-migrations#109]
Just a while ago, the first stable release of GraalVM Community Edition was released - https://github.com/oracle/graal/releases/tag/vm-19.0.0 It is numbered with version 19.0.0, which is quite confusing compared to the release candidates versioning schema. Another interesting fact is that it adds an early adopter windows support.

I open this ticket to ask you - what version tag for GraalVM CE 19.0.0 should we use? It sounds like it should be 

```
19.0.0-graalvm
```

or maybe

```
19.0.0-graal-ce
```

to indicate that this is a community edition. However, this might be confusing - does it mean it runs on Java 19? (It uses Java 8u212.) All other Java candidates shipped with SDKMAN use the postfix version to inform the user what is the underlying Java version. GraalVM breaks this convention.

It could be also introduced as a separate candidate, for instance `sdk install graalvm 19.0.0`, but it would interfere with `java` candidate. I could live with the fact that executing

```
$ sdk use graalvm 19.0.0
```

changes my $JAVA_HOME to the GraalVM candidate, overriding whatever `sdk use java ...` I did before the previous command.

Just wanted to ask for your opinion before creating the pull request with the update. /cc @marc0der @ilopmar

**Comment by wololock** [comment]
One more thing worth mentioning. Extracting GraalVM to a separate SDKMAN candidate may have more sense than keeping it under the `java` candidate. The thing is that GraalVM ships tools like `npm`, `node` or `js`. 

```
$ sdk use java 1.0.0-rc-16-grl

Using java version 1.0.0-rc-16-grl in this shell.

$ ls $JAVA_HOME/bin
appletviewer  gu    jar        java   javadoc  javap         jcmd      jdb    jhat   jjs   jps         js         jstack  jstatd     keytool  native2ascii  node  orbd     policytool  rmic  rmiregistry  serialver   tnameserv  wsgen     xjc
extcheck      idlj  jarsigner  javac  javah    java-rmi.cgi  jconsole  jdeps  jinfo  jmap  jrunscript  jsadebugd  jstat   jvisualvm  lli      native-image  npm   pack200  polyglot    rmid  schemagen    servertool  unpack200  wsimport
```

When we switch to GraalVM Java distribution, we also override those binaries as a side effect. I experienced that before when I tried to use `hexo` in the terminal with `java:1.0.0-rc-16-grl`. The `node` shipped by GraalVM threw multiple exceptions. Luckily, I quickly realized that I was running `hexo` from the terminal with the GraalVM nodejs, so I switched to the new session with my default nodejs version.

I think it would make much more sense if we extract GraalVM from the regular Java candidates in this case.

**Comment by marc0der** [comment]
@wololock this is a tricky problem that we have been facing from the start. Adding GraalVM to the Java candidate was the easiest thing at the time. The main problem with creating it as a separate Candidate is that the `java` and `javac` of GraalVM would probably shadow the Java equivalents. It would result in all sorts of issues. Also, you probably need `JAVA_HOME` set for GraalVM to work properly (not sure about that).

This would mean that we might need to introduce some way to enable/disable a candidate, which could cause a lot confusion for people who don't know how that works. This was what led me down the road of including it under Java in the first place.

The main problem with having it as 19.0.0 under the Java candidate is with the list view. This is something that I want to fix in any case by having separate sections on Java's list view per vendor. That would definitely solve the problem at least in the short term. wdyt?

**Comment by ilopmar** [comment]
I agree with Marco. At the end GraalVM is another Java version that you can use to compile and run your java apps *without* using native-image tool. I think it makes sense that include the new version just like we did we the previous release candidates.

As they explain here: https://medium.com/graalvm/announcing-graalvm-19-4590cf354df8:
> We plan to release updates to it: GraalVM 19.1, 19.2 and so on at least once per quarter. These updates will include bug fixes and stability and performance improvements, but no major new features. When necessary, a one-off hotfix GraalVM 19.x.1, 19.x.2, etc. release will be published.

There will be new versions at least per quarter + the bugfixing. Also they will continue shipping beta versions `20.0-betaN` that we also need to include.

So, as a summary I think we could add this version as `19.0.0-graal-ce` inside the same Java candidate.

**Comment by wololock** [comment]
You're right. Introducing GraalVM as a separate candidate could be confusing when defining a default `java` and `graalvm`. It seems to be more pragmatic to keep them together, especially that most people usually use a different JDK as a default one, and only switch to GraalVM when needed. The only question is - how to tag the new version? If we want to support GraalVM future beta releases, we need to come up with a tag that fits in 15 characters.

**Comment by marc0der** [comment]
The changes I will make to the backend will lift the 15 character restriction. I'll add an additional optional classifier for `vendor` to the version collection in the database. That will also allow us to `groupBy` the vendor when rendering the custom Java list view that I'll start working on next.

**Comment by wololock** [comment]
Sounds good! :+1: Let us know if there is anything we can help you with.

**Comment by ilopmar** [comment]
Sounds good! @wololock do you want to send the PR for the new version? It's just 15 characters so we're good at this moment.

**Comment by wololock** [comment]
@ilopmar I made last 2 or 3 pull requests. It's your turn 😉

**Comment by wololock** [comment]
Btw, Cedric posted this today - https://twitter.com/CedricChampeau/status/1127169184713068544 It seems like 19.0.0 release introduced some small breaking changes compared to 1.0.0-RC16. We can wait with the deletion of the remaining RCs until the next release or two.

**Comment by ilopmar** [comment]
PR submitted: https://github.com/sdkman/sdkman-db-migrations/pull/111
