### ISSUE TITLE
New Java view doesn't show local versions

### ISSUE THREAD

**Issue by ananni13** [sdkman/sdkman-db-migrations#121]
With the latest updates on improving candidates handling, the list view doesn't show local versions anymore, previously marked with "+". They are still usable but don't show up in the list.

Maybe it can be added at the end like another vendor?

```
================================================================================
Available Java Versions
================================================================================
 Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------------
 ...
 java.net      |     | 14.ea.1      | open    |            | 14.ea.1-open        
               |     | 13.ea.25     | open    |            | 13.ea.25-open       
               |     | 12.0.1       | open    |            | 12.0.1-open         
               |     | 11.0.2       | open    |            | 11.0.2-open         
               |     | 10.0.2       | open    |            | 10.0.2-open         
               |     | 9.0.4        | open    |            | 9.0.4-open          
local          |     |              |         | installed  | <name-you-used>
               |     |              |         | installed  | <name-you-used>
```

**Comment by marc0der** [comment]
It seems like a bug was introduced yes, the restriction here being that the local Java version needs to be added with a name suffix ending in a vendor identifier. At the moment, the supported vendor suffixes are `adpt`, `amzn`, `grl`, `librca`, `open`, `sapmchn`, `zulu` and `zulufx`. Could you try re-adding the version with one of these suffixes to see if it works? eg. `myversion-open`
