### ISSUE TITLE
Please change AdoptOpenJDK openj9 to 64bit on Windows

### ISSUE THREAD

**Issue by abcfy2** [sdkman/sdkman-db-migrations#280]
https://github.com/sdkman/sdkman-db-migrations/blob/006159dd03ade0c472d1a4828a1086ab688d6a5f/src/main/scala/io/sdkman/changelogs/java/AdoptOpenJdkMigrations.scala#L479

I find on Windows use

```
sdk i java 8.0.252.j9-adpt
```

Will get 32bit version instead of 64bit.

```
$ curl -sI https://api.sdkman.io/2/broker/download/java/8.0.252.j9-adpt/mingw64_nt-10.0-19041
HTTP/1.1 302 Found
Server: nginx/1.15.12
Date: Wed, 01 Jul 2020 15:18:27 GMT
Content-Length: 0
Connection: keep-alive
location: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u252-b09_openj9-0.20.0/OpenJDK8U-jdk_x86-32_windows_openj9_8u252b09_openj9-0.20.0.zip
```

You can see the download URL  redirect to 32bit version

**Comment by marc0der** [comment]
Hi @abcfy2, yep seems like someone submitted the wrong binary. Feel free to raise a PR to fix this if you are able.

**Comment by marc0der** [comment]
You should be able to use the existing db migration to do this:
https://github.com/sdkman/sdkman-db-migrations/blob/master/src/main/scala/io/sdkman/changelogs/java/AdoptOpenJdkMigrations.scala#L455-L488

It seems like only the windows version is affected.

**Comment by abcfy2** [comment]
OK. I've already raised a PR. But I don't know whether it can work. I'm not familiar with mongobee. Please check.
