### ISSUE TITLE
Add Alibaba Dragonwell JDK

### ISSUE THREAD

**Issue by eddumelendez** [sdkman/sdkman-db-migrations#361]
[Alibaba Dragonwell](http://dragonwell-jdk.io/) is another JDK distribution.

Current support is for Linux for the versions below:

- 8 https://github.com/alibaba/dragonwell8/releases/tag/dragonwell-8.4.4_jdk8u262-ga
- 11 https://github.com/alibaba/dragonwell11/releases/tag/dragonwell-11.0.8.3_jdk-11.0.8-ga

**Comment by eddumelendez** [comment]
@marc0der WDYT?

**Comment by marc0der** [comment]
Looks good, although the Windows JDK8 might be problematic for now. The linux variants are tarballs so should work just fine.
