### ISSUE TITLE
OpenJDK 11.0.8 Removed?

### ISSUE THREAD

**Issue by erikthered** [sdkman/sdkman-db-migrations#374]
This PR seems to have removed 11.0.8 from Java.net/OpenJDK: https://github.com/sdkman/sdkman-db-migrations/pull/371

It is now at 11.0.2. Was this intentional?

**Comment by marc0der** [comment]
I believe that openjdk doesn't have an official 11.0.8 release, as they generally don't maintain legacy Java versions. Openjdk is more concerned with bleeding edge releases. 

What you were seeing was the AdoptOpenJDK 11.0.8 erroneously released under openjdk. I suggest always using adopt, this also being the default installation on sdkman.

**Comment by erikthered** [comment]
Thanks for the clarification. I did some research on this today and it does indeed seem to be the case.
