### ISSUE TITLE
Add "visible" field to "versions" collection with default value "true"

### ISSUE THREAD

**Issue by helpermethod** [sdkman/sdkman-db-migrations#399]
In order to allow `soft-deletes` a `visible` flag should be added to the `versions` collection.  
If code in the sdkman/sdk-candidates project breaks due to the schema change, it should  be fixed in a way to stay backwards-compatible (i.e. no visible change to the behaviour).

This is the first step in resolving #170.

**Comment by marc0der** [comment]
An alternative to consider is to make this field optional, having its default set to `true`. That means that we only need to mark the field as `visible=false` as required explicitly.

**Comment by helpermethod** [comment]
@marc0der That's exactly what I had in mind 😄 .
