### ISSUE TITLE
feature: add support for installing flyway

### ISSUE THREAD

**Issue by rfigueroa** [sdkman/sdkman-db-migrations#414]
Since sdkman may start to support liquidbase to https://github.com/sdkman/sdkman-db-migrations/issues/389, flyway could also be a candidate

**Comment by marc0der** [comment]
@rfigueroa This can be done with some simple database migrations on our sdkman-db-migrations project if you are up for a challenge.

**Comment by helpermethod** [comment]
Hi, @rfigueroa,

Sadly the `flyway` tar has the same problem as the `liquibase` tar, i.e. no `bin` folder underneath the root folder.

**Comment by rfigueroa** [comment]
How can asoman handle this scenario?

**Comment by helpermethod** [comment]
Sadly there's not much that SDKMAN! can do here. You best bet would be to open an issue in Liquibase repository. They may be open to change the TAR's structure to be compatible with SDKMAN!.

**Comment by rfigueroa** [comment]
since the flyway team give a good reason for not having a bin folder, and the same could be said for the liquidbase distribution tar, are there options on sdkman on how to handle these scenarios ?

**Comment by marc0der** [comment]
The industry standard for JVM related SDK distributions is to have the same layout as the JDK does. We rely on this as a sensible default. We do support some outliers like JMC, but much work and testing goes into making this work.

If you feel very strongly about this and are up for the challenge, please chat to me on Slack so I can give you some pointers.
