### ISSUE TITLE
Error publishing GraalVM 20.3

### ISSUE THREAD

**Issue by morki** [sdkman/sdkman-db-migrations#429]
There was an error in Travis build and GraalVM 20.3. is not available to install by SDKMAN.

**Comment by marc0der** [comment]
@eddumelendez It seems like there is a problem with the [GraalVM 20.3.0 OSX link](https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.3.0/graalvm-ce-java11-darwin-amd64-20.3.0-signed.tar.gz).

**Comment by eddumelendez** [comment]
this is fixed now
