### ISSUE TITLE
Add support for older Scala versions

### ISSUE THREAD

**Issue by Eugenio-Liso** [sdkman/sdkman-db-migrations#443]
Hi all!

Right now, SDKMAN! supports Scala SDK versions starting from 2.11.0. Since there are a lot of projects out there that are still using older versions, is that possible to add support for 2.10.X?  

I think that should be enough, since the latest 2.9.X version (2.9.3) has been tagged in 2013, so it's pretty old.

**Comment by marc0der** [comment]
Hi @Eugenio-Liso, the more versions the merrier. Please feel free to add them by raising a PR on this project.
