### ISSUE TITLE
Add support for getting Java version series

### ISSUE THREAD

**Issue by helpermethod** [sdkman/sdkman-db-migrations#445]
In order to hide older versions of a version series (e.g. all Java `11`, Java `8`, Java `9` versions) a new method should be provided which, when given

* a `platform`
* a `majorVersion` (e.g. 11)
* a `vendorSuffix` (e.g. `zulu-fx`, `zulu`)

returns a list of `previous` versions, which can then be `hidden`.

**Comment by marc0der** [comment]
Is candidate relevant here? Java is the only candidate that works in this way and requires hiding. Wdyt?

**Comment by helpermethod** [comment]
Correct.

**Comment by helpermethod** [comment]
Sorry, this should be part of `sdkman-mongodb-persistence`.
