### ISSUE TITLE
Feature: [Ballerina.io (BVM/JBallerina) Support]

### ISSUE THREAD

**Issue by kkeker** [sdkman/sdkman-db-migrations#451]
- [+] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**

Please add the [Ballerina.IO](https://ballerina.io) toolkit installation. This is a kind of metalanguage (like Scala or Kotlin) on top of the JVM and it would be logical if SDKMan would support the Ballerina.IO installation.

**Comment by helpermethod** [comment]
Hi @kkeker,

Ballerina is already part of SDKMAN!, though it's currently missing the latest stable release.

```
✦ ❯ sdk list ballerina
================================================================================
Available Ballerina Versions
================================================================================
     swan-lake-p3















================================================================================
+ - local version
* - installed
> - currently in use
================================================================================
```

**Comment by kkeker** [comment]
But the database is not updated.
There is only one release candidate.
There is no stable version or other release candidates.

**Comment by marc0der** [comment]
@kkeker If you need other versions, please feel free to add it yourself by raising a PR against this repo. All instructions can be found in the README.md.
