### ISSUE TITLE
Download is failing, why?

### ISSUE THREAD

**Issue by chkpnt** [sdkman/sdkman-db-migrations#494]
I'm trying to figure out, why a download is failing. In my case, it's about the installation of "java 16-sapmchn".

```
➜  BitBook git:(main) sdk install java 16-sapmchn

Downloading: java 16-sapmchn

In progress...

###################################################################################################################################### 100.0%
Download has failed, aborting!

Can not install java 16-sapmchn at this time...
```

I haven't found a debug mode in SDKMAN!, so I tried to understand this repository to find the corresponding download url. I've found [SapMachineMigrations.scala](../blob/master/src/main/scala/io/sdkman/changelogs/java/SapMachineMigrations.scala), but I don't get it: there is no entry for "16-sapmchn". So where is it declared?

**Comment by marc0der** [comment]
I've just managed to install it without any issues, could it be a network problem?
Please feel free to chat with us on Slack if the problem persists.
