### ISSUE TITLE
Feature: Add Apache Ant 1.10.10

### ISSUE THREAD

**Issue by iemejia** [sdkman/sdkman-db-migrations#502]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**

**Comment by helpermethod** [comment]
Hi @iemejia!

I've moved your issue to the `sdkman-db-migrations` project. 

This is the place where users can contribute new versions or candidates.
Instructions for adding a new version can be found in the README.

If you have any questions, feel free to ask!

**Comment by iemejia** [comment]
Thanks @helpermethod opened #503 can you help me review it or find someone who can, thanks!
