### ISSUE TITLE
Bug: Azul 16.0.1 on java/darwinarm64 is stale.  Needs update to build 30+19 for macOS 11.4

### ISSUE THREAD

**Issue by michaelabuckley** [sdkman/sdkman-db-migrations#517]
**Bug report**

The java 16.0.1-zulu version installed on Mac arm fails to start on Mac 11.4

I can't tell from your docs who is responsible for updating your files. Is Azul is managing their release, or do you have a data side?  Sorry if this is the wrong target.  I've let them know too.

Caused by https://bugs.openjdk.java.net/browse/JDK-8267235 upstream.

**To reproduce**

- `sdk install java 16.0.1-zulu`
- `javac -version`

**System info**

Mac on 11.4
~/tmp % uname -a                                                                                                                                  15:54:28
Darwin mb-m1 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64
~/tmp % sdk version                                                                                                                               15:54:31
SDKMAN 5.11.4+709
~/tmp % zsh --version                                                                                                                             15:54:44
zsh 5.8 (x86_64-apple-darwin20.0)

**Comment by eddumelendez** [comment]
@michaelabuckley can you check again? binaries were updated for zulu arm

**Comment by michaelabuckley** [comment]
Works after uninstall, flush, and install.  Couldn't figure out how to upgrade an installed version.

Matches my copy of the April 20 .pkg
```
michael@mb-m1 cdr % sdk use java 16.0.1-0zulupkg

Using java version 16.0.1-0zulupkg in this shell.
michael@mb-m1 cdr % java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment Zulu16.30+19-CA (build 16.0.1+9)
OpenJDK 64-Bit Server VM Zulu16.30+19-CA (build 16.0.1+9, mixed mode)

michael@mb-m1 cdr % sdk use java 16.0.1-zulu 

Using java version 16.0.1-zulu in this shell.
michael@mb-m1 cdr % java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment Zulu16.30+19-CA (build 16.0.1+9)
OpenJDK 64-Bit Server VM Zulu16.30+19-CA (build 16.0.1+9, mixed mode)
```

**Comment by emartynov** [comment]
The same feedback I want to give is that I have to flush before getting a new build. Can SDK check the checksum also for updating the same version binaries?
