### ISSUE TITLE
Consider using Disco API for JDKs metadata

### ISSUE THREAD

**Issue by sideeffffect** [sdkman/sdkman-db-migrations#520]
The foojay Disco API is a general purpose API to discover builds of OpenJDK from different distributions.
It should allow for automation instead of manually maintaining own metadata.
https://github.com/foojay2020/discoapi

**Comment by marc0der** [comment]
Hi @sideeffffect, we are already using the Disco API for all our JDK releases.

**Comment by sideeffffect** [comment]
Oh, that's good to hear! I tried to look around the source code of some of the SDKMAN repositories, but it wasn't obvious to me.
:+1:
