### ISSUE TITLE
Regression: Java 17 early access builds are no longer available

### ISSUE THREAD

**Issue by SethTisue** [sdkman/sdkman-db-migrations#543]
I'm experiencing this on both Linux and macOS. Something changed within the last week or so -- it was working before.

A Linux example is https://app.travis-ci.com/github/scala/scala-xml/jobs/536511441 where `sdk list java` only shows `17.ea.3.pma` which is unsuitable (it's a Project Panama build). Until recently, `17.ea.28` was one of the choices offered.

The same thing happens for me on macOS; `sdk list java` has:

```
               | >>> | 17.ea.28     | open    | local only | 17.ea.28-open       
               |     | 17.ea.3.pma  | open    |            | 17.ea.3.pma-open    
```

here the `local only` shows that until recently `17.ea.28` was available but now is not.

I hope I'm reporting this in the right place (I'm not well versed in SDKMAN stuff).

**Comment by eddumelendez** [comment]
java 17 has been released and it's available now via sdkman. There is an issue on my side when openjdk enters to RC phase, I will fix it for the java 18.
