### ISSUE TITLE
chang J'Bang to JBang

### ISSUE THREAD

**Issue by maxandersen** [sdkman/sdkman-db-migrations#566]
I would like to get the J'Bang name updated to JBang as I did that everywhere else already but I'm not spotting how to do so in the migrations.

Any pointers would be great and I'll make a PR.

**Comment by marc0der** [comment]
That has now been corrected @maxandersen

I left you DM in the SDKMAN Slack some time ago. Would you mind responding if you have a minute?

**Comment by maxandersen** [comment]
Great! It's still listed in description with J'Bang - not a biggie but JBang would be more consistent.
