### ISSUE TITLE
[Question] Removed migrations during cleanup

### ISSUE THREAD

**Issue by xshyamx** [sdkman/sdkman-db-migrations#581]
Hi,

A lot of migrations were cleaned up during this commit   [801f6d4](https://github.com/sdkman/sdkman-db-migrations/commit/801f6d4ae5ed9a5fd2de4713cc19a76c5b432f06). Is it required to add all removed versions when adding a new version? Or it is sufficient to add just the new versions for the candidate?

Is this [PR](https://github.com/sdkman/sdkman-db-migrations/compare/master...xshyamx:jmeter-update?expand=1) sufficient to add new versions of JMeter to sdkman?

**Comment by marc0der** [comment]
Hi @xshyamx, unfortunately this won't work as the changeset number always needs to be unique across each changelog.

You can read about how Mongobee works on their [project page] (https://github.com/mongobee/mongobee).

**Comment by xshyamx** [comment]
Thanks. Will change the PR accordingly
