### ISSUE TITLE
Consider changing suffix of ZuluFX candidates to `-zulufx` instead of `-fx-zulu`

### ISSUE THREAD

**Issue by vpavic** [sdkman/sdkman-db-migrations#62]
ZuluFX candidates were added in recently merged #53 - IMO candidate suffix should be changed to `-zulufx` instead of `-fx-zulu`, as this is both consistent with [Azul's naming](https://www.azul.com/downloads/zulu/zulufx/) and also reads better since it would provide more consistency between Zulu's candidates.

**Comment by marc0der** [comment]
Sounds fair, we'll need to make some changes to accommodate it in the backend though.

**Comment by marc0der** [comment]
I've made all the necessary changes and run a migration to remain them to `-zulufx`.
