### ISSUE TITLE
Bug: Cannot install Maven 3.8.7

### ISSUE THREAD

**Issue by rickie** [sdkman/sdkman-db-migrations#636]
**Bug report**
We are unable to install Maven 3.8.7 with the SDKMAN CLI.
It's probably using the wrong URL to try and download 3.8.7, namely: 
```
https://dlcdn.apache.org/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.zip
```
Instead of:
```
https://archive.apache.org/dist/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.zip
```

**To reproduce**
```
$ sdk install maven 3.8.7

Downloading: maven 3.8.7

In progress...

############################################################################################################################################################################################################ 100,0%
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/rick/.sdkman/tmp/maven-3.8.7.zip or
        /home/rick/.sdkman/tmp/maven-3.8.7.zip.zip, and cannot find /home/rick/.sdkman/tmp/maven-3.8.7.zip.ZIP, period.

Stop! The archive was corrupt and has been removed! Please try installing again.
```

**System info**
```
$ lsb_release -a
Description:	Ubuntu 20.04.5 LTS
Release:	20.04

$ zsh --version
zsh 5.8 (x86_64-ubuntu-linux-gnu)

$ sdk version
SDKMAN!
script: 5.18.0
native: 0.1.3
```

**Comment by tessneau** [comment]
I'm running into the same issue, copying over my report from slack https://sdkman.slack.com/archives/CJTNQA94M/p1680886237947579 . It does seem to be searching in the wrong URL as @rickie mentioned.

shell 
```
zsh 5.8 (x86_64-apple-darwin21.0)
```
sdkman version
```
SDKMAN!
script: 5.18.1
native: 0.2.2
```

**Comment by helpermethod** [comment]
`dlcdn.apache.org` seems to only keep the latest minor versions:

https://dlcdn.apache.org/maven/maven-3/

@aalmiray Would switching to `archive.apache.org` work?

**Comment by aalmiray** [comment]
Bummer. We definitely have to update the db.

**Comment by tessneau** [comment]
in the meantime, is there a good way that I can install maven 3.8.7 directly and move it to a folder where sdkman can pick it up?

**Comment by aalmiray** [comment]
Recommended link is https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/

**Comment by marc0der** [comment]
Hey all, I ran a migration that fixed all the URLs for maven. Please let me know if that does the trick for you.
