### ISSUE TITLE
Feature: Add support for `jextract`

### ISSUE THREAD

**Issue by overheadhunter** [sdkman/sdkman-db-migrations#663]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] I've had a conversation on the [#cli-development](https://sdkman.slack.com/app_redirect?channel=cli-development) Slack channel about this request.

**Feature request**

The `jextract` tool used to be part of the JDK in older builds of Project Panama but [has been externalized](https://github.com/openjdk/jextract) to decouple the release cycle. It helps generating Java bindings from C header files using the FFM API (currently still in preview).

You might want to have multiple versions of jextract installed at the same time, each of which compatible with a different JDK. SDKMAN! would simplify managing those installations.

**Comment by marc0der** [comment]
Yep, I see no problem in supporting jextract, although we would need to do some additional work as it is only distributed as `.tgz`.

**Comment by helpermethod** [comment]
@marc0der Prebuilt binaries are distributed at `.tar.gz`.

**Comment by marc0der** [comment]
We will need to make some changes to hooks to handle this. After that we can merge. I'll see what I can do over the weekend.

**Comment by marc0der** [comment]
Okay, I've deployed the changes to sdkman-hooks. I'll unblock your other PR @helpermethod

**Comment by marc0der** [comment]
Hi @overheadhunter, we released Jextract but realised it includes `java` and `javac` too. This is a big problem because it clobbers the `java` binaries provided by our `java` candidate. I will need to pull `jextract` for now until this issue is resolved.

**Comment by helpermethod** [comment]
I've asked on the jextract-dev mailing list if they could remove java and javac from the binaries but it doesn't seem that easy

```
Hi,
While removing javac should be doable, I think dropping the java
launcher is more problematic, as that launcher is called by the jextract
launcher.

So, doing something like that would require a deeper restructuring of
the build layout I'm afraid.

Maurizio
```

So I fear we can't support jextract any time soon.

**Comment by overheadhunter** [comment]
I have seen Maurizio's answer as well.

I guess adding a different dir to `PATH`, which solely contains a symlink to the jextract binary is not an option?

**Comment by marc0der** [comment]
It's a big pity, and we can always revisit this if they find a different way of repackaging their tools.

**Comment by overheadhunter** [comment]
Great news, looking forward to it!

**Comment by marc0der** [comment]
It would be great to test these binaries with a local install before we add jextract @helpermethod

**Comment by helpermethod** [comment]
> It would be great to test these binaries with a local install before we add jextract @helpermethod 

Tested the latest version on Ubuntu and it  seems to work fine.

**Comment by marc0der** [comment]
Okay, so is it a tar archive? Do they have a zip variant? If it's only tar, we'll need to override it in the hooks service.

> Looking at the extracted TAR, I wonder if the version shouldn't just include the OpenJDK version

We're you referring to the version in the containing folder?

**Comment by helpermethod** [comment]
> Okay, so is it a tar archive? Do they have a zip variant? If it's only tar, we'll need to override it in the hooks service.
> 
> > Looking at the extracted TAR, I wonder if the version shouldn't just include the OpenJDK version
> 
> We're you referring to the version in the containing folder?

Yes, it's only distributed as a TAR, so we also need to extend the hooks service.

**Comment by helpermethod** [comment]
@marc0der It seems you already made the necessary changes to the `sdkman-hooks` service

**Comment by marc0der** [comment]
Yeah, I was just rereading the thread above and saw it ☺️

**Comment by helpermethod** [comment]
@overheadhunter Jextract is now officially supported and can be installed via 

    sdk install jextract 22.ea.5
