### ISSUE TITLE
Added VisualVM 2.1.10？

### ISSUE THREAD

**Issue by linghengqian** [sdkman/sdkman-db-migrations#708]
- I looked at PRs like #705 and the process for updating VisualVM seems to be manual. Also, the VisualVM maintainers are not involved in the distribution on `SDKMAN!`.
- VisualVM 2.1.10 has been released, this new version is mainly to support JDK23. Does this mean a separate PR is needed? See https://visualvm.github.io/download.html .

**Comment by helpermethod** [comment]
Hi @linghengqian,

SDKMAN! supports two types of candidates, vendor-driven (via an API) and community-driven, via migrations. VisualVM is community-driven, so as you expected, it needs new migrations in the form of a PR.

Would you like submit a PR for the new version?

**Comment by linghengqian** [comment]
> Hi @linghengqian,
> 
> SDKMAN! supports two types of candidates, vendor-driven (via an API) and community-driven, via migrations. VisualVM is community-driven, so as you expected, it needs new migrations in the form of a PR.
> 
> Would you like submit a PR for the new version?

- Honestly I don't really understand the API convention of `SDKMAN!`. Should it be like #709?

**Comment by helpermethod** [comment]
Yes, the PR looks fine. New versions for an existing candidate need a new migration with an incremented migration number.

The whole process is documented in detail here:
https://github.com/oracle/visualvm/releases/download/2.1.10/visualvm_2110.zip
