### ISSUE TITLE
Amazon Corretto 11.0.2 (GA)

### ISSUE THREAD

**Issue by joschi** [sdkman/sdkman-db-migrations#74]
Amazon has release Corretto 11.0.2 (GA):
https://aws.amazon.com/about-aws/whats-new/2019/03/amazon-corretto-11-is-now-generally-available/

Due to the current naming scheme, I'm not sure how to add it to SDKMan, though.
The complete version specifier is "11.0.2.9.3" for the GA version and was "11.0.2.9.1" before. Unfortunately, SDKMan only covered the first 3 elements ("11.0.2"):
https://github.com/sdkman/sdkman-db-migrations/blob/3a60b3518c9d053f01e172942bf1a13ffe04f532/src/main/scala/io/sdkman/changelogs/JavaMigrations.scala#L501-L508

Any ideas?

Download URLs:
https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html

**Comment by marc0der** [comment]
It's very unfortunate that Amazon have decided to disregard the standard versioning scheme adopted by everyone else (Major, Minor, Patch). It will break sdkman's sorting algorithm, so I would need to do some work in the backend prior to merging to accommodate this.

I'll let you know when I've completed the work.

**Comment by joschi** [comment]
@marc0der Would something like "11.0.2ga-amzn" be working?

**Comment by marc0der** [comment]
It wouldn't, because what happens if they do another release of 11.0.2.x (which is highly likely).

**Comment by joschi** [comment]
@marc0der You're completely right. In this case, maybe something such as "11.0.2_3-amzn" would work? It's still within the 15 character length limit of SDKMan, if I remember correctly.

**Comment by marc0der** [comment]
Nope, that's still not consistent with the rest. Like I said, I'll have to make some changes in the backend first. It would probably need to be `11.0.2.9.3-amzn`.

**Comment by joschi** [comment]
Issue is outdated as SDKMAN is distributing "11.0.3.j9-adpt" and "11.0.3.hs-adpt".
