### ISSUE TITLE
Add kotlin-native as a new candidate

### ISSUE THREAD

**Issue by cyparu** [sdkman/sdkman-db-migrations#86]
With [Kotlin](https://kotlinlang.org) already available into SDKMan for long time (**sdk list kotlin**) and Kotlin/Native improving fast it will be great to be able to install it using SDKMan as well (**sdk install kotlin-native**). 
Here are some relevat Kotlin/Native resources:
- https://kotlinlang.org/docs/tutorials/native/basic-kotlin-native-app.html#obtaining-the-compiler
- https://github.com/JetBrains/kotlin-native/releases
- https://github.com/JetBrains/kotlin/releases/tag/v1.3.30

**Comment by helpermethod** [comment]
Hi, @cyparu,

this is certainly doable. 

But I wonder if it wouldn't be better if Jetbrains themselves would upload new Kotlin Native versions via the Vendor API, like they already seem to do with Kotlin.

@marc0der What do you think?

**Comment by helpermethod** [comment]
Hi @cyparu,

if you want to make this happen please upvote https://youtrack.jetbrains.com/issue/KT-44288.

**Comment by helpermethod** [comment]
Had a little conversation with the JB guys and the gist is that Kotlin Native is currently not in a state
where it makes sense to use it outside of Gradle, but they may reconsider it in the future.

https://youtrack.jetbrains.com/issue/KT-44288
